---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: mreddy967/helloworldkube
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace:default
  labels:
    app: hello
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: hello
  type: NodePort
